### ISSUE TITLE
Unclear How to Start Using RunRoller

### ISSUE THREAD

**Issue by fuzzygroup** [keichan34/runroller#10]
Hi, 

I just forked your code and am trying to bring up a local installation on OSX for experimentation.  I thought that what I'd do is start by updating your readme and I'll get you a pull request shortly for that once this is answered.

What surprised me tho is that exactly how to start things up is unclear.  I can get things running by doing: iex -S mix

and then a curl command against the local installation will work.  But I would have thought something like 

mix run

would start things.  Now, that said, I'm new to Elixir and this could be a classic noob mistake in which case I apologize.

**Comment by keichan34** [comment]
You were almost there! `mix run` technically works, but it will halt when the application has finished booting (which is not desirable in this case). To prevent it from exiting, you can run `mix run --no-halt`. I've updated the README with instructions on how to get started -- please let me know if something is unclear and I'll fix the README.

By the way, `iex -S mix` is great for development / debugging because you have a command line window in the running environment of your app, but for production `mix run` or using something like `exrm` is recommended.
